"""Public API for zmqruntime.

Package-root imports stay lightweight: heavy runtime modules (client, server,
execution, message stacks) load on first attribute access instead of at
import time. Declaration-only consumers (configuration modules, DTO layers)
therefore do not pay the zmq/psutil/threading import cost.
"""

from __future__ import annotations

from importlib.metadata import version as _distribution_version
from typing import TYPE_CHECKING

__version__ = _distribution_version("zmqruntime")

_LAZY_EXPORTS: dict[str, str] = {
    "GlobalAckListener": "zmqruntime.ack_listener",
    "EndpointConnectionCancelledError": "zmqruntime.client",
    "EndpointConnectionPolicy": "zmqruntime.client",
    "EndpointProcessGroup": "zmqruntime.client",
    "EndpointShutdownMode": "zmqruntime.client",
    "EndpointShutdownResult": "zmqruntime.client",
    "ZMQClient": "zmqruntime.client",
    "TransportMode": "zmqruntime.config",
    "ZMQConfig": "zmqruntime.config",
    "CancelRequest": "zmqruntime.messages",
    "ControlErrorResponse": "zmqruntime.messages",
    "ControlMessageType": "zmqruntime.messages",
    "ControlResponse": "zmqruntime.messages",
    "EndpointApplication": "zmqruntime.messages",
    "EndpointApplicationCompatibility": "zmqruntime.messages",
    "EndpointApplicationCompatibilityError": "zmqruntime.messages",
    "EndpointControlCapability": "zmqruntime.messages",
    "ExecuteRequest": "zmqruntime.messages",
    "ExecuteResponse": "zmqruntime.messages",
    "ExecutionRecord": "zmqruntime.messages",
    "ExecutionStatus": "zmqruntime.messages",
    "ExecutionStatusSnapshot": "zmqruntime.messages",
    "ImageAck": "zmqruntime.messages",
    "MessageFields": "zmqruntime.messages",
    "PongResponse": "zmqruntime.messages",
    "ProcessExit": "zmqruntime.messages",
    "ProcessIdentity": "zmqruntime.messages",
    "ProcessResourceUsage": "zmqruntime.messages",
    "ProgressRegistrationRequest": "zmqruntime.messages",
    "ProgressUnregistrationRequest": "zmqruntime.messages",
    "QueuedExecutionInfo": "zmqruntime.messages",
    "ResponseType": "zmqruntime.messages",
    "ROIMessage": "zmqruntime.messages",
    "RunningExecutionInfo": "zmqruntime.messages",
    "ServerRole": "zmqruntime.messages",
    "ShapesMessage": "zmqruntime.messages",
    "SocketType": "zmqruntime.messages",
    "StatusRequest": "zmqruntime.messages",
    "TaskPhase": "zmqruntime.messages",
    "TaskProgress": "zmqruntime.messages",
    "TaskStatus": "zmqruntime.messages",
    "WorkerState": "zmqruntime.messages",
    "validate_progress_payload": "zmqruntime.messages",
    "ExecutionLifecycleEngineABC": "zmqruntime.execution",
    "ExecutionProgressObservation": "zmqruntime.execution",
    "ExecutionResponseDiagnostic": "zmqruntime.execution",
    "ExecutionSubmissionResponse": "zmqruntime.execution",
    "ExecutionWaiter": "zmqruntime.execution",
    "ExecutionWaitResult": "zmqruntime.execution",
    "InMemoryExecutionLifecycleEngine": "zmqruntime.execution",
    "ProgressStreamSubscriber": "zmqruntime.execution",
    "WaitPolicy": "zmqruntime.execution",
    "EventRegistryABC": "zmqruntime.progress",
    "EventRegistryMutation": "zmqruntime.progress",
    "EventRegistryMutationKind": "zmqruntime.progress",
    "GenericAxisProjection": "zmqruntime.progress",
    "GenericExecutionProjection": "zmqruntime.progress",
    "GenericPlateProjection": "zmqruntime.progress",
    "LatestEventRegistry": "zmqruntime.progress",
    "ProgressProjectionAdapterABC": "zmqruntime.progress",
    "build_execution_projection": "zmqruntime.progress",
    "GlobalQueueTrackerRegistry": "zmqruntime.queue_tracker",
    "QueueTracker": "zmqruntime.queue_tracker",
    "serve_forever": "zmqruntime.runner",
    "ZMQServer": "zmqruntime.server",
    "EndpointStartupObserver": "zmqruntime.startup",
    "EndpointStartupPhase": "zmqruntime.startup",
    "EndpointStartupPresentationTarget": "zmqruntime.startup",
    "EndpointStartupStatus": "zmqruntime.startup",
    "EndpointStartupStatusCallback": "zmqruntime.startup",
    "EndpointStartupStatusMonitor": "zmqruntime.startup",
    "EndpointStartupStatusRead": "zmqruntime.startup",
    "EndpointStartupStatusReader": "zmqruntime.startup",
    "EndpointStartupStatusWriter": "zmqruntime.startup",
    "CallbackSubscription": "zmqruntime.subscription",
    "SubscriptionABC": "zmqruntime.subscription",
    "OperationCancellation": "zmqruntime.timeouts",
    "OperationDeadline": "zmqruntime.timeouts",
    "OperationTimeoutError": "zmqruntime.timeouts",
    "DataControlPortPair": "zmqruntime.transport",
    "DataControlPortPairAuthority": "zmqruntime.transport",
    "TcpDataControlPortPair": "zmqruntime.transport",
    "TcpDataControlPortPairAuthority": "zmqruntime.transport",
    "TransportEndpoint": "zmqruntime.transport",
    "get_control_port": "zmqruntime.transport",
    "get_control_url": "zmqruntime.transport",
    "get_default_transport_mode": "zmqruntime.transport",
    "get_ipc_socket_path": "zmqruntime.transport",
    "get_zmq_transport_url": "zmqruntime.transport",
    "is_port_in_use": "zmqruntime.transport",
    "ping_control_port": "zmqruntime.transport",
    "remove_ipc_socket": "zmqruntime.transport",
    "resolve_transport_mode": "zmqruntime.transport",
    "wait_for_endpoint_ready": "zmqruntime.transport",
    "wait_for_server_ready": "zmqruntime.transport",
    "ViewerAckPolicy": "zmqruntime.viewer_protocol",
    "ViewerAckResponsePayload": "zmqruntime.viewer_protocol",
    "ViewerBatchContextWireField": "zmqruntime.viewer_protocol",
    "ViewerBatchDisplayPayload": "zmqruntime.viewer_protocol",
    "ViewerBatchItemPayload": "zmqruntime.viewer_protocol",
    "ViewerBatchItemWireField": "zmqruntime.viewer_protocol",
    "ViewerBatchItemWireMapping": "zmqruntime.viewer_protocol",
    "ViewerBatchMessageExtraInput": "zmqruntime.viewer_protocol",
    "ViewerBatchMessageExtraPayload": "zmqruntime.viewer_protocol",
    "ViewerBatchMessageImages": "zmqruntime.viewer_protocol",
    "ViewerBatchMessagePayload": "zmqruntime.viewer_protocol",
    "ViewerBatchMessageType": "zmqruntime.viewer_protocol",
    "ViewerBatchMessageWirePayload": "zmqruntime.viewer_protocol",
    "ViewerBatchWireField": "zmqruntime.viewer_protocol",
    "ViewerComponentMetadataPayload": "zmqruntime.viewer_protocol",
    "ViewerComponentMode": "zmqruntime.viewer_protocol",
    "ViewerComponentModeGroups": "zmqruntime.viewer_protocol",
    "ViewerControlReplyHeader": "zmqruntime.viewer_protocol",
    "ViewerControlReplyPayload": "zmqruntime.viewer_protocol",
    "ViewerControlResponseField": "zmqruntime.viewer_protocol",
    "ViewerDisplayConfigWireField": "zmqruntime.viewer_protocol",
    "ViewerProtocolStatus": "zmqruntime.viewer_protocol",
    "ViewerTransportEndpoint": "zmqruntime.viewer_protocol",
    "ViewerWireMapping": "zmqruntime.viewer_protocol",
    "ViewerWirePayload": "zmqruntime.viewer_protocol",
    "ViewerWireScalar": "zmqruntime.viewer_protocol",
    "ViewerWireValue": "zmqruntime.viewer_protocol",
    "viewer_wire_key": "zmqruntime.viewer_protocol",
    "ViewerInstance": "zmqruntime.viewer_state",
    "ViewerState": "zmqruntime.viewer_state",
    "ViewerStateManager": "zmqruntime.viewer_state",
    "get_or_create_viewer": "zmqruntime.viewer_state",
}

__all__ = [
    "EndpointConnectionCancelledError",
    "EndpointConnectionPolicy",
    "EndpointProcessGroup",
    "EndpointShutdownMode",
    "EndpointShutdownResult",
    "ZMQClient",
    "TransportMode",
    "ZMQConfig",
    "CancelRequest",
    "ControlErrorResponse",
    "ControlResponse",
    "ControlMessageType",
    "EndpointControlCapability",
    "EndpointApplication",
    "EndpointApplicationCompatibility",
    "EndpointApplicationCompatibilityError",
    "ExecuteRequest",
    "ExecuteResponse",
    "ExecutionRecord",
    "ExecutionStatusSnapshot",
    "RunningExecutionInfo",
    "QueuedExecutionInfo",
    "ExecutionStatus",
    "ImageAck",
    "MessageFields",
    "ProcessExit",
    "ProcessIdentity",
    "PongResponse",
    "ProcessResourceUsage",
    "ProgressRegistrationRequest",
    "ProgressUnregistrationRequest",
    # Generic types
    "TaskProgress",
    "TaskPhase",
    "TaskStatus",
    "WorkerState",
    "ServerRole",
    "ResponseType",
    "ROIMessage",
    "ShapesMessage",
    "SocketType",
    "StatusRequest",
    "validate_progress_payload",
    "QueueTracker",
    "GlobalQueueTrackerRegistry",
    "serve_forever",
    "ZMQServer",
    "EndpointStartupObserver",
    "EndpointStartupPhase",
    "EndpointStartupPresentationTarget",
    "EndpointStartupStatus",
    "EndpointStartupStatusCallback",
    "EndpointStartupStatusRead",
    "EndpointStartupStatusMonitor",
    "EndpointStartupStatusReader",
    "EndpointStartupStatusWriter",
    "OperationCancellation",
    "OperationDeadline",
    "OperationTimeoutError",
    "DataControlPortPair",
    "DataControlPortPairAuthority",
    "TcpDataControlPortPair",
    "TcpDataControlPortPairAuthority",
    "TransportEndpoint",
    "get_control_port",
    "get_control_url",
    "get_default_transport_mode",
    "get_ipc_socket_path",
    "get_zmq_transport_url",
    "is_port_in_use",
    "ping_control_port",
    "remove_ipc_socket",
    "resolve_transport_mode",
    "wait_for_server_ready",
    "wait_for_endpoint_ready",
    "ViewerState",
    "ViewerStateManager",
    "ViewerInstance",
    "get_or_create_viewer",
    "ViewerAckPolicy",
    "ViewerAckResponsePayload",
    "ViewerBatchContextWireField",
    "ViewerBatchDisplayPayload",
    "ViewerBatchItemPayload",
    "ViewerBatchItemWireMapping",
    "ViewerBatchItemWireField",
    "ViewerBatchMessageType",
    "ViewerBatchMessageImages",
    "ViewerBatchMessageExtraInput",
    "ViewerBatchMessageExtraPayload",
    "ViewerBatchMessagePayload",
    "ViewerBatchMessageWirePayload",
    "ViewerBatchWireField",
    "ViewerDisplayConfigWireField",
    "ViewerControlReplyHeader",
    "ViewerControlReplyPayload",
    "ViewerControlResponseField",
    "ViewerComponentMode",
    "ViewerComponentModeGroups",
    "ViewerComponentMetadataPayload",
    "ViewerProtocolStatus",
    "ViewerTransportEndpoint",
    "ViewerWireMapping",
    "ViewerWirePayload",
    "ViewerWireScalar",
    "ViewerWireValue",
    "viewer_wire_key",
    "ExecutionLifecycleEngineABC",
    "ExecutionProgressObservation",
    "InMemoryExecutionLifecycleEngine",
    "ProgressStreamSubscriber",
    "ExecutionWaiter",
    "WaitPolicy",
    "ExecutionResponseDiagnostic",
    "ExecutionSubmissionResponse",
    "ExecutionWaitResult",
    "EventRegistryABC",
    "EventRegistryMutation",
    "EventRegistryMutationKind",
    "CallbackSubscription",
    "SubscriptionABC",
    "LatestEventRegistry",
    "GenericAxisProjection",
    "GenericPlateProjection",
    "GenericExecutionProjection",
    "ProgressProjectionAdapterABC",
    "build_execution_projection",
]


def __getattr__(name: str):
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module 'zmqruntime' has no attribute {name!r}")
    import importlib

    value = getattr(importlib.import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))
