"""Public API for zmqruntime."""

from __future__ import annotations

__version__ = "0.1.13"

from zmqruntime.ack_listener import GlobalAckListener
from zmqruntime.client import ZMQClient
from zmqruntime.config import TransportMode, ZMQConfig
from zmqruntime.execution import (
    ExecutionLifecycleEngineABC,
    ExecutionResponseDiagnostic,
    ExecutionSubmissionResponse,
    ExecutionWaiter,
    ExecutionWaitResult,
    InMemoryExecutionLifecycleEngine,
    ProgressStreamSubscriber,
    WaitPolicy,
)
from zmqruntime.messages import (
    CancelRequest,
    ControlMessageType,
    ExecuteRequest,
    ExecuteResponse,
    ExecutionRecord,
    ExecutionStatus,
    ExecutionStatusSnapshot,
    ImageAck,
    MessageFields,
    PongResponse,
    ProcessExit,
    ProcessIdentity,
    ProgressRegistrationRequest,
    ProgressUnregistrationRequest,
    QueuedExecutionInfo,
    ResponseType,
    ROIMessage,
    RunningExecutionInfo,
    ServerCapability,
    ServerInfo,
    ShapesMessage,
    SocketType,
    StatusRequest,
    TaskPhase,
    # Generic types
    TaskProgress,
    TaskStatus,
    WorkerState,
    validate_progress_payload,
)
from zmqruntime.progress import (
    EventRegistryABC,
    GenericAxisProjection,
    GenericExecutionProjection,
    GenericPlateProjection,
    LatestEventRegistry,
    ProgressProjectionAdapterABC,
    build_execution_projection,
)
from zmqruntime.queue_tracker import GlobalQueueTrackerRegistry, QueueTracker
from zmqruntime.runner import serve_forever
from zmqruntime.server import ZMQServer
from zmqruntime.transport import (
    TcpDataControlPortPair,
    TcpDataControlPortPairAuthority,
    coerce_transport_mode,
    get_control_port,
    get_control_url,
    get_default_transport_mode,
    get_ipc_socket_path,
    get_zmq_transport_url,
    is_port_in_use,
    ping_control_port,
    remove_ipc_socket,
    wait_for_server_ready,
)
from zmqruntime.viewer_protocol import (
    ViewerAckPolicy,
    ViewerAckResponsePayload,
    ViewerBatchContextWireField,
    ViewerBatchDisplayPayload,
    ViewerBatchItemPayload,
    ViewerBatchItemWireField,
    ViewerBatchItemWireMapping,
    ViewerBatchMessageExtraInput,
    ViewerBatchMessageExtraPayload,
    ViewerBatchMessageImages,
    ViewerBatchMessagePayload,
    ViewerBatchMessageType,
    ViewerBatchMessageWirePayload,
    ViewerBatchWireField,
    ViewerComponentMetadataPayload,
    ViewerComponentMode,
    ViewerComponentModeGroups,
    ViewerControlReplyHeader,
    ViewerControlReplyPayload,
    ViewerControlResponseField,
    ViewerDisplayConfigWireField,
    ViewerProtocolStatus,
    ViewerTransportEndpoint,
    ViewerWireMapping,
    ViewerWirePayload,
    ViewerWireScalar,
    ViewerWireValue,
    viewer_wire_key,
)
from zmqruntime.viewer_state import (
    ViewerInstance,
    ViewerState,
    ViewerStateManager,
    get_or_create_viewer,
)

__all__ = [
    "GlobalAckListener",
    "ZMQClient",
    "TransportMode",
    "ZMQConfig",
    "CancelRequest",
    "ControlMessageType",
    "ExecuteRequest",
    "ExecuteResponse",
    "ExecutionRecord",
    "ExecutionStatusSnapshot",
    "RunningExecutionInfo",
    "QueuedExecutionInfo",
    "ExecutionStatus",
    "ImageAck",
    "MessageFields",
    "ProcessExit",
    "ProcessIdentity",
    "PongResponse",
    "ProgressRegistrationRequest",
    "ProgressUnregistrationRequest",
    # Generic types
    "TaskProgress",
    "TaskPhase",
    "TaskStatus",
    "WorkerState",
    "ServerInfo",
    "ServerCapability",
    "ResponseType",
    "ROIMessage",
    "ShapesMessage",
    "SocketType",
    "StatusRequest",
    "validate_progress_payload",
    "QueueTracker",
    "GlobalQueueTrackerRegistry",
    "serve_forever",
    "ZMQServer",
    "TcpDataControlPortPair",
    "TcpDataControlPortPairAuthority",
    "coerce_transport_mode",
    "get_control_port",
    "get_control_url",
    "get_default_transport_mode",
    "get_ipc_socket_path",
    "get_zmq_transport_url",
    "is_port_in_use",
    "ping_control_port",
    "remove_ipc_socket",
    "wait_for_server_ready",
    "ViewerState",
    "ViewerStateManager",
    "ViewerInstance",
    "get_or_create_viewer",
    "ViewerAckPolicy",
    "ViewerAckResponsePayload",
    "ViewerBatchContextWireField",
    "ViewerBatchDisplayPayload",
    "ViewerBatchItemPayload",
    "ViewerBatchItemWireMapping",
    "ViewerBatchItemWireField",
    "ViewerBatchMessageType",
    "ViewerBatchMessageImages",
    "ViewerBatchMessageExtraInput",
    "ViewerBatchMessageExtraPayload",
    "ViewerBatchMessagePayload",
    "ViewerBatchMessageWirePayload",
    "ViewerBatchWireField",
    "ViewerDisplayConfigWireField",
    "ViewerControlReplyHeader",
    "ViewerControlReplyPayload",
    "ViewerControlResponseField",
    "ViewerComponentMode",
    "ViewerComponentModeGroups",
    "ViewerComponentMetadataPayload",
    "ViewerProtocolStatus",
    "ViewerTransportEndpoint",
    "ViewerWireMapping",
    "ViewerWirePayload",
    "ViewerWireScalar",
    "ViewerWireValue",
    "viewer_wire_key",
    "ExecutionLifecycleEngineABC",
    "InMemoryExecutionLifecycleEngine",
    "ProgressStreamSubscriber",
    "ExecutionWaiter",
    "WaitPolicy",
    "ExecutionResponseDiagnostic",
    "ExecutionSubmissionResponse",
    "ExecutionWaitResult",
    "EventRegistryABC",
    "LatestEventRegistry",
    "GenericAxisProjection",
    "GenericPlateProjection",
    "GenericExecutionProjection",
    "ProgressProjectionAdapterABC",
    "build_execution_projection",
]
